platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
  pod 'RxBluetoothKit' # working with bluetooth
  pod 'SwiftGRPC' # support compiled proto files
  pod 'CryptoSwift' # data parsing helpers
end

target 'SwiftBleRpc' do
  shared_pods
  
  target 'SwiftBleRpcTests' do
    inherit! :search_paths
    shared_pods
    
    pod 'Nimble' # helpers for testing
    pod 'Cuckoo', :git => 'https://github.com/Brightify/Cuckoo.git', :branch => 'internal-issues' # generate mock file
  end

end
